---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubernetes-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  url: ssh://git@github.com/JonSchaeffer/kubernetes-secrets
  ref:
    branch: main
  # secretRef:
  # name: secrets-deploy-key
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetes-secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  force: false
  interval: 1m0s
  path: ./homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-secrets
