apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: maystor
  namespace: maystor
spec:
  interval: 1m
  chart:
    spec:
      chart: mayastor
      reconcileStrategy: Revision
      version: "2.5.0"
      sourceRef:
        kind: HelmRepository
        name: maystor
        namespace: flux-system
      interval: 1m
  values:
