apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: homelab
spec:
  interval: 1m
  chart:
    spec:
      chart: cloudnative-pg
      reconcileStrategy: Revision
      #version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
      interval: 1m
  values:
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: homelab
  spec:
    instances: 3
    storage:
      size: 5Gi
