apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 1m
  chart:
    spec:
      chart: tailscale-operator
      reconcileStrategy: Revision
      #version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      interval: 1m
  values:
    apiServerProxyConfig:
      mode: "noauth"