apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace:
spec:
  interval: 1m
  chart:
    spec:
      chart: vaultwarden
      reconcileStrategy: Revision
      targetNamespace: homelab
      createNamespace: true
      #version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: flux-system
      interval: 1m
  values:
