apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: homelab
spec:
  interval: 1m
  chart:
    spec:
      targetNamespace: homelab
      chart: vaultwarden
      reconcileStrategy: Revision
      #version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: vaultwarden
        namespace: flux-system
      interval: 1m
  values:
    domain: "vaultwarden.jonathanschaeffer.com"
